# Generated by Django 6.0.4 on 2026-05-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='average_score',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='best_score',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
