# Generated by Django 6.0.4 on 2026-05-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_topicinfo_topic_quizresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='registration_number',
            field=models.CharField(default=None, max_length=10, null=True, unique=True),
        ),
    ]
