# Generated by Django 6.0.4 on 2026-05-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_average_score_customuser_best_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='average_score',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='best_score',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
