# Generated by Django 6.0.4 on 2026-05-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='topic_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
