# Generated by Django 6.0.4 on 2026-05-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_customuser_average_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='average_score',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='best_score',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
