# Generated by Django 6.0.4 on 2026-05-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_customuser_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
