# Generated by Django 6.0.4 on 2026-05-06 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_subject_options_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='topic',
            name='learning_objectives',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='short_note',
        ),
        migrations.AddField(
            model_name='topic',
            name='estimated_minutes',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='topic',
            name='question_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='TopicInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('short_note', models.TextField()),
                ('learning_objectives', models.TextField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_infos', to='core.topic')),
            ],
        ),
    ]
