# Generated by Django 6.0.4 on 2026-05-10 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_quizquestion_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='average_score',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='best_score',
        ),
    ]
